In [1]:
import torch
from torch_geometric.data import Batch, Data, InMemoryDataset

In [2]:
da1 = torch.load("PB_seal/processed/SEAL_train_data_didrnl.pt")

In [6]:
class tds(InMemoryDataset):
    def __init__(self, data, slices):
        super().__init__()
        self.data = data
        self.slices = slices

In [7]:
ds1 = tds(*da1)

In [9]:
ds1[0].z

tensor([0, 1, 4, 3, 3, 3, 3, 4, 4, 4, 3, 4, 3, 6, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 4, 4, 3, 4, 3, 4, 3, 3, 3, 3, 4, 4, 3, 3, 3, 3, 3, 4, 3, 3, 3,
        3, 3, 2, 4, 4, 3, 3, 3, 3, 3, 4, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 4, 3, 3])

In [30]:
batch = ds2[0]

In [32]:
from seal_models import PlabelingZOGIN

In [33]:
mod = PlabelingZOGIN(256, 3, 10, ds2, False, None)

In [34]:
z = batch.z
z = (torch.tensor([[1], [2]], dtype=z.dtype, device=z.device) == z.unsqueeze(0)).to(torch.long)

In [36]:
z_emb = mod.z_embedding(z)

In [38]:
z_emb.shape

torch.Size([2, 26, 256])

In [34]:
import scipy.sparse as spsp

In [38]:
def data2graph(data):
    node_id = data.node_id
    ei = node_id[data.edge_index]
    ea = data.edge_weight
    return spsp.csr_matrix((ea.numpy(), (ei[0].numpy(), ei[1].numpy())))

def data2z(data):
    node_id = data.node_id
    ei = node_id[data.edge_index]
    ea = data.edge_weight
    return spsp.csr_matrix((ea.numpy(), (ei[0].numpy(), ei[1].numpy())))

In [55]:
torch.all(ds1.slices['edge_index'] == ds1.slices["edge_weight"])

tensor(True)

In [58]:
ds2.slices

defaultdict(dict,
            {'x': tensor([      0,      26,      95,  ..., 4963652, 4963672, 4963696]),
             'edge_index': tensor([       0,      216,      812,  ..., 98349626, 98349878, 98350010]),
             'y': tensor([     0,      1,      2,  ..., 146327, 146328, 146329]),
             'edge_weight': tensor([       0,      216,      812,  ..., 98383572, 98383824, 98383956]),
             'z': tensor([      0,      26,      95,  ..., 4963652, 4963672, 4963696]),
             'node_id': tensor([      0,      26,      95,  ..., 4963652, 4963672, 4963696])})

In [57]:
ds2.slices['edge_index'] == ds2.slices["edge_weight"]

tensor([ True,  True,  True,  ..., False, False, False])

In [60]:
for i in range(len(ds1)):
    try:
        ret = data2graph(ds1[i]) - data2graph(ds2[i])
        ret.eliminate_zeros()
        if ret.nnz >0:
            print(i)
    except:
        print(i)

2
4
8
9
10
11
12
16
20
22
32
33
34
37
39
42
44
51
52
53
54
56
57
58
60
61
64
66
73
75
76
79
80
83
89
94
95
96
104
110
111
114
116
117
119
120
125
126
127
132
134
135
136
140
144
149
154
157
158
159
161
163
164
169
172
174
177
180
181
186
187
191
193
196
198
199
203
205
206
211
216
221
225
229
230
242
243
244
246
247
248
250
254
255
256
268
269
270
273
276
277
281
283
289
291
294
295
298
304
305
306
309
314
318
321
323
324
325
327
328
329
330
333
337
338
341
342
345
346
348
354
355
358
359
361
364
368
369
373
377
378
379
380
381
382
383
384
388
393
397
402
404
423
424
426
427
431
432
433
442
443
444
446
447
448
456
459
461
464
465
467
474
476
480
481
484
486
496
501
505
506
508
511
512
513
514
520
521
523
525
526
527
529
530
533
537
538
541
545
548
550
551
556
561
562
564
572
576
579
583
586
591
592
593
594
596
599
600
603
607
610
612
614
625
629
632
645
648
651
652
655
656
661
662
663
665
666
667
672
675
679
680
682
687
688
689
690
691
694
695
697
698
703
708
716
719
722
735
736
740
74

In [30]:
ds1[0].edge_weight

tensor([4., 1., 1., 8., 1., 1., 1., 1., 1., 1., 1., 1., 3., 1., 3., 1., 1., 3.,
        1., 1., 3., 1., 1., 1., 3., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 4., 6., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1., 3., 1., 1., 1., 1.,
        1., 1., 5., 1., 3., 1., 1., 4., 3., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        2., 2., 1., 2., 3., 2., 1., 1., 1., 2., 5., 1., 2., 2., 1., 1., 8., 6.,
        2., 2., 1., 1., 1., 8., 6., 1., 1., 4., 2., 5., 1., 1., 1., 1., 2., 1.,
        1., 1., 2., 1., 1., 1., 1., 4., 1., 1., 1., 3., 2., 1., 1., 2., 2., 1.,
        3., 1., 1., 8., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2.,
        1., 1., 3., 1., 1., 1., 1., 1., 4., 2., 8., 1., 2., 1., 1., 1., 1., 1.,
        1., 1., 3., 1., 6., 2., 2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 2., 1., 1., 1., 1., 1., 1., 2., 2., 1., 3., 1., 1., 2., 5., 8., 1.])

In [29]:
ds2[0].edge_weight

tensor([1, 1, 4, 8, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 4, 1, 1, 1, 1, 2, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 6, 1, 1, 2, 1, 3, 2, 2,
        1, 1, 1, 1, 2, 1, 2, 1, 1, 5, 2, 6, 1, 8, 2, 3, 1, 2, 2, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 5, 1, 1, 1, 3, 1, 4, 1, 3, 1,
        1, 1, 1, 3, 8, 1, 1, 1, 2, 1, 1, 1, 1, 8, 4, 6, 1, 2, 5, 1, 1, 1, 2, 6,
        1, 3, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 1,
        2, 8, 1, 1, 4, 1, 1, 2, 1, 3, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1,
        1, 1, 3, 1, 1, 3, 3, 1, 1, 1, 3, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        2, 1, 8, 5, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1])

In [18]:
b0 = torch.load("batch0.pt", map_location="cpu")
b1 = torch.load("batch1.pt", map_location="cpu")

In [17]:
def collatepos(pos: torch.Tensor):
    '''
    pos (batch_size, 3), the third column is subgraph size
    '''
    tpos = pos[:, :2].clone()
    tpos[1:] += torch.cumsum(pos[:-1, 2], dim=0).unsqueeze(-1)
    return tpos

In [21]:
b0.pos

tensor([[132,  48, 215],
        [ 28,  12,  40],
        [ 33,  29,  45],
        [ 21,  37,  54],
        [  2,  50,  51],
        [  5,   6,  32],
        [ 23,  22,  27],
        [ 80,  37,  90],
        [ 55,  16,  60],
        [ 24,  25,  28],
        [ 53,  70, 108],
        [185, 116, 225],
        [  3,  11,  17],
        [  3,   5,   7],
        [ 82,  29,  95],
        [ 10,  11,  16],
        [  2,  13,  62],
        [  1,   0,   5],
        [  1,  10,  16],
        [ 29,  69,  71],
        [  8,  74, 109],
        [136, 118, 147],
        [  4,  13,  19],
        [ 18,  94, 120],
        [  5,   0,  15],
        [  7,   1,  15],
        [ 14,  18,  19],
        [ 25,   0,  28],
        [  5,  21,  27],
        [ 44,   7,  49],
        [105,  60, 139],
        [ 16,  19,  23],
        [  6,   1,  51],
        [  4,  13,  26],
        [110,  72, 160],
        [ 11,   0,  15],
        [ 65,  55, 112],
        [ 18,  21,  23],
        [ 20,  19,  26],
        [ 37,   3,  41],


In [20]:
collatepos(b0.pos)

tensor([[ 132,   48],
        [ 243,  227],
        [ 288,  284],
        [ 321,  337],
        [ 356,  404],
        [ 410,  411],
        [ 460,  459],
        [ 544,  501],
        [ 609,  570],
        [ 638,  639],
        [ 695,  712],
        [ 935,  866],
        [ 978,  986],
        [ 995,  997],
        [1081, 1028],
        [1104, 1105],
        [1112, 1123],
        [1173, 1172],
        [1178, 1187],
        [1222, 1262],
        [1272, 1338],
        [1509, 1491],
        [1524, 1533],
        [1557, 1633],
        [1664, 1659],
        [1681, 1675],
        [1703, 1707],
        [1733, 1708],
        [1741, 1757],
        [1807, 1770],
        [1917, 1872],
        [1967, 1970],
        [1980, 1975],
        [2029, 2038],
        [2161, 2123],
        [2222, 2211],
        [2291, 2281],
        [2356, 2359],
        [2381, 2380],
        [2424, 2390],
        [2429, 2443],
        [2689, 2661],
        [2718, 2719],
        [2746, 2735],
        [2762, 2755],
        [2

In [26]:
torch.all(collatepos(b0.pos)[:64] == collatepos(b1.pos))

tensor(True)

In [16]:
torch.all(b0.pos[:64] == b1.pos)

tensor(True)

In [21]:
mask = b0.edge_index<3767

In [23]:
torch.all(mask[0] == mask[1])

tensor(True)

In [11]:
torch.all(b0.batch[b0.batch<64] == b1.batch)

tensor(True)

In [3]:
b0

DataBatch(x=[9797], edge_index=[2, 304410], pos=[256, 3], batch=[9797], ptr=[257])

In [1]:
from impl import Utils
from torch_geometric.utils import to_undirected, add_self_loops, coalesce
from torch_geometric.utils import k_hop_subgraph, is_undirected, degree
import torch
from importlib import reload
from impl import SegUtils
from ogb.linkproppred import PygLinkPropPredDataset
from torch_sparse import SparseTensor
import torch_sparse
from torch_geometric.utils import coalesce

In [9]:
dataset = PygLinkPropPredDataset(f"ogbl-collab", "data")

In [13]:
torch.sum(dataset[0].edge_weight.flatten() == 1)

tensor(2154296)

In [156]:
dataset = PygLinkPropPredDataset(f"ogbl-collab", "data")
data = dataset[0]
edge_index = data.edge_index
device = torch.device("cuda")
num_node = dataset[0].num_nodes
split_edge = dataset.get_edge_split()
adj_t = SparseTensor.from_edge_index(to_undirected(edge_index),
                                     sparse_sizes=(num_node, num_node))
adj_t = torch_sparse.set_diag(adj_t)  #原来没有set_diag

In [50]:
boosted_ei = add_self_loops(edge_index)[0]

In [154]:
boosted_deg = degree(edge_index.flatten(), num_node) + 1

In [157]:
pos = split_edge["valid"]["edge_neg"][:1000]

In [158]:
dls = SegUtils.precomputersubgs(None, num_node, None, adj_t, edge_index,
                                boosted_deg,
                                pos, False, 100,
                                1)

In [159]:
ds = SegUtils.SubGDataset(dls)

In [167]:
ds.data.edge_index

tensor([], size=(0, 198867), dtype=torch.int64)

In [164]:
ds.slices["edge_index"].shape

torch.Size([1001])

In [147]:
adj_t_cuda = adj_t.cuda()
boosted_deg_cuda = boosted_deg.cuda()
pos_cuda = pos[:1000].cuda()

In [148]:
import time

In [151]:
torch.cuda.synchronize(device)
t1 = time.time()
for i in range(100):
    SegUtils.get_subg(None, num_node, adj_t_cuda, boosted_ei, boosted_deg_cuda,
    3, pos_cuda, None)
torch.cuda.synchronize(device)
t2 = time.time()
print(t2-t1)

153.9835147857666


In [117]:
ei = torch.tensor([[0, 1], [1, 2], [2, 3], [3, 0]], dtype=torch.long).t()
ea = torch.tensor([0.5, 0.5, 0.5, 0.5])
ei, ea = to_undirected(ei, ea)
num_node = 4
pos = torch.tensor([[0, 2], [1, 3]])

In [71]:
subgroot = SegUtils.pos2subg(pos)

In [72]:
subgmask = SegUtils.rootedsubg(ei, num_node, subgroot, 1)

In [73]:
nums = torch.tensor([5, 3, 2])
SegUtils.get_offset(nums, num_node)

tensor([0, 0, 0, 0, 0, 4, 4, 4, 8, 8])

In [74]:
SegUtils.expand(torch.arange(12).unsqueeze(-1), 1, 3)

tensor([[ 0,  0,  0],
        [ 1,  1,  1],
        [ 2,  2,  2],
        [ 3,  3,  3],
        [ 4,  4,  4],
        [ 5,  5,  5],
        [ 6,  6,  6],
        [ 7,  7,  7],
        [ 8,  8,  8],
        [ 9,  9,  9],
        [10, 10, 10],
        [11, 11, 11]])

In [77]:
SegUtils.expand(ei, 1, 2)

tensor([[0, 0, 1, 1, 2, 2, 3, 3, 0, 0, 1, 1, 2, 2, 3, 3],
        [1, 3, 0, 2, 1, 3, 0, 2, 1, 3, 0, 2, 1, 3, 0, 2]])

In [78]:
reload(SegUtils)

<module 'impl.SegUtils' from '/home/wxy/PlabelingTrick/impl/SegUtils.py'>

In [94]:
reload(SegUtils)

<module 'impl.SegUtils' from '/home/wxy/PlabelingTrick/impl/SegUtils.py'>

In [118]:
segei, idx_rev, other = SegUtils.renumberg(
    subgmask, 
    SegUtils.subgmasks2g(subgmask, ei), 
    segpos)

torch.Size([52])
torch.Size([52]) torch.Size([10])


In [119]:
segpos  = SegUtils.pos2segpos(pos, num_node)

In [120]:
segnum_node = idx_rev.shape[0]
dsegei = SegUtils.delete_cluster(segnum_node, segpos, segei)

In [122]:
segpos

tensor([[0, 2],
        [5, 7]])

In [121]:
dsegei

tensor([[0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 1, 3, 4, 6],
        [1, 3, 0, 2, 1, 3, 0, 2, 5, 7, 4, 6, 5, 7, 4, 6, 1, 3, 4, 6]])

In [92]:
ei

tensor([0, 1, 2, 3, 4, 5, 6, 7])

In [4]:
import Dataset
from impl import Utils
import torch

In [5]:
pos = torch.tensor([[0,1],[1,2],[2,3], [3,1]])

In [6]:
Utils.convert_pos(pos, 4)

tensor([[0, 1],
        [1, 2],
        [2, 3],
        [3, 1]])


(tensor([0, 1, 2, 3]),
 tensor([[ 4,  1],
         [ 9,  6],
         [14, 11],
         [ 7, 13]]))

In [2]:
ds = Dataset.load_dataset("Cora")
split_edge = Utils.do_edge_split(ds)

In [4]:
from torch_geometric.utils import is_undirected

In [11]:
ei = split_edge["train"]["edge"]
split_edge["train"]["edge"] = Utils.to_directed(ei)
split_edge["train"]["edge_neg"] = split_edge["train"][
    "edge_neg"][:, :split_edge["train"]["edge"].shape[1]]

In [13]:
pair = Utils.edge2ds(split_edge["train"]["edge"], split_edge["train"]["edge_neg"])

In [18]:
ds[0].x.shape[0]

2708

In [24]:
from importlib import reload
reload(Utils)

<module 'impl.Utils' from '/home/wxy/PlabelingTrick/impl/Utils.py'>

In [23]:
import torch
torch.unique(ei[:, :16], return_inverse=True)

(tensor([   0,    1,    2,    3,    4,    5,  332,  652,  654, 1016, 1256, 1454,
         1629, 1666, 1761, 1862, 1986, 2176, 2544, 2582]),
 tensor([[ 0,  0,  1,  1,  1,  2,  2,  2,  2,  2,  3,  4,  4,  4,  4,  5],
         [15, 19,  2,  7,  8,  1,  6, 11, 13, 16, 18,  9, 10, 14, 17, 12]]))

In [26]:
ei[:, :16]

tensor([[   0,    0,    1,    1,    1,    2,    2,    2,    2,    2,    3,    4,
            4,    4,    4,    5],
        [1862, 2582,    2,  652,  654,    1,  332, 1454, 1666, 1986, 2544, 1016,
         1256, 1761, 2176, 1629]])

In [25]:
Utils.convert_pos(ei[:, :16], ds[0].x.shape[0])

(tensor([   0,    1,    2,    3,    4,    5,  332,  652,  654, 1016, 1256, 1454,
         1629, 1666, 1761, 1862, 1986, 2176, 2544, 2582]),
 tensor([[   0, 1862],
         [   0, 2582],
         [   1,    2],
         [   1,  652],
         [   1,  654],
         [   2,    1],
         [   2,  332],
         [   2, 1454],
         [   2, 1666],
         [   2, 1986],
         [   3, 2544],
         [   4, 1016],
         [   4, 1256],
         [   4, 1761],
         [   4, 2176],
         [   5, 1629]]))